FROM python:3.11.5-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD [ "gunicorn", "server:app", "--worker-class", "uvicorn.workers.UvicornWorker" ,"--bind", "0.0.0.0:8080", "--workers", "4"]